import Head from 'next/head'
import SideBar from './SideBar'
import Header from './Header'
import { observer } from 'mobx-react-lite'
import Login from './auth/Login'
import Registration from './auth/Registration'
import { singIn, singUp } from '../utils.js/auth'
import { ErrorAlert, MessageAlert } from './Alert'
import { useContext, useEffect } from 'react'
import { StoreContext } from '../pages/_app'
import cookie from 'js-cookie'
import jwt_decode from "jwt-decode";
import { useRouter } from 'next/router'

function MainLayout({ children }) {

   const { user } = useContext(StoreContext)

   useEffect(() => {
      const token = cookie.get('token')
      if (token) {
         const userData = jwt_decode(token)
         user.setUser(userData)
      }
   }, [])

   return (
      <>
         <Head>
            <title>BlueTrade.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
         </Head>
         <body id='body'>
            <main className='box_main '>
               <Header />
               <SideBar />
               {children}
            </main>
            <ErrorAlert />
            <MessageAlert />
         </body>
      </>
   )
}

export default observer(MainLayout)

